version: '3.8'

services:
  api:
    build: .
    container_name: backend_api
    ports:
      - "6900:6900"
    volumes:
      - .:/app              
      - /app/node_modules
    command: npm run dev
    environment:
      - PORT=6900
      - MONGO_URI=mongodb://mongo:27017/finnance
    depends_on:
      - mongo
    networks:
      - backend-net

  mongo:
    image: mongo:6
    container_name: backend_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

volumes:
  mongo-data:

networks:
  backend-net:
    driver: bridge
