version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend_api_dev
    ports:
      - "6900:6900"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=6900
      - MONGO_URI=mongodb://mongo:27017/finnance
    depends_on:
      - mongo
    networks:
      - backend-net

  mongo:
    image: mongo:6
    container_name: backend_mongo_dev
    restart: always
    ports:
      - "6800:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - backend-net

  mongo-client: 
    image: mongo-express:latest
    container_name: backend_mongo_client
    restart: always
    depends_on:
      - mongo
    networks:
      - backend-net
    environment:
      - ME_CONFIG_MONGODB_SERVER=backend_mongo_dev
      - ME_CONFIG_MONGODB_PORT=27017
    ports:
      - "6801:8081"

volumes:
  mongo-data:

networks:
  backend-net:
    driver: bridge
